#!/usr/bin/env php
<?php

namespace spinitron\c2ct;

require __DIR__ . '/CollationToCharsetTable.php';
$c2cc = new CollationToCharsetTable(require __DIR__ . '/config.php');

$script = array_shift($argv);
$command = array_shift($argv);
switch ($command) {
    case 'newtable':
        $c2cc->newTable();
        break;
    case 'editable':
        echo $c2cc->getEditable(!in_array('-d', $argv), in_array('-c', $argv));
        break;
    case 'utf8':
    case 'sphinx':
    case 'rules':
        $method = 'get' . ucfirst($command);
        if (in_array('-', $argv)) {
            $c2cc->parseEditableTable(file_get_contents('php://stdin'), !in_array('-d', $argv));
        }
        echo $c2cc->$method();
        break;
    default:
        echo <<<TXT
Usage:
    $script { newtable | editable [-c][-d] | utf8 [-d][-] | sphinx [-d][-] | rules [-d][-] }

Commands:
    newtable  Populate a MySQL collation table with characters
    editable  Write human-editable charset table given the populated collation table to stdout
    utf8      Write human-readable charset table using UTF-8 to stdout
    sphinx    Write human-readable Sphinx charset_table to stdout
    rules     Write compressed Sphinx charset_table to stdout

Options:
    -c  Sort human-editable charset table in by codepoint rather than collation
    -d  Codepoints in decimal rather than hex
    -   Rread a human-editable charset table from stdin instead of the MySQL collation table

TXT;
        exit(1);
}
