<?php

// Overrides the default values of public properties of CollationToCharsetTable.
// See CollationToCharsetTable's property doc-blocks for documentation.
return [
    'pdoDsn' => 'mysql:host=127.0.0.1',
    'pdoUser' => 'root',
    'pdoPass' => require __DIR__ . '/pdo_password.php',

    'collateRanges' => [
        [0x0021, 0x007E],
        [0x00A1, 0x00FF],
        [0x0100, 0x04FF],
        //[0x0500, 0x1FFF],
        //[0x2070, 0xA7FF],
        //[0xA800, 0xD7FF],
        //[0xE000, 0xEFFF],
        //[0xF000, 0xFFFF],
        //[0x10000, 0x10FFF],
        //[0x11000, 0x111FF],
        //[0x12000, 0x124FF],
        //[0x13000, 0x134FF],
        //[0x17000, 0x18AFF],
        //[0x1D000, 0x1DAFF],
        //[0x1F000, 0x1F9FF],
        //[0x1F600, 0x1F64F],
    ],
    'maxFoldRun' => 8,
    'excludeCharacterCategories' => [
        \IntlChar::CHAR_CATEGORY_UNASSIGNED,
        \IntlChar::CHAR_CATEGORY_SPACE_SEPARATOR,
        \IntlChar::CHAR_CATEGORY_LINE_SEPARATOR,
        \IntlChar::CHAR_CATEGORY_PARAGRAPH_SEPARATOR,
        \IntlChar::CHAR_CATEGORY_CONTROL_CHAR,
        \IntlChar::CHAR_CATEGORY_FORMAT_CHAR,
        \IntlChar::CHAR_CATEGORY_SURROGATE,
        \IntlChar::CHAR_CATEGORY_DASH_PUNCTUATION,
        \IntlChar::CHAR_CATEGORY_START_PUNCTUATION,
        \IntlChar::CHAR_CATEGORY_END_PUNCTUATION,
        \IntlChar::CHAR_CATEGORY_CONNECTOR_PUNCTUATION,
        \IntlChar::CHAR_CATEGORY_OTHER_PUNCTUATION,
        \IntlChar::CHAR_CATEGORY_INITIAL_PUNCTUATION,
        \IntlChar::CHAR_CATEGORY_FINAL_PUNCTUATION,
    ],
    'excludeProperties' => [
        \IntlChar::PROPERTY_DASH,
        \IntlChar::PROPERTY_DEFAULT_IGNORABLE_CODE_POINT,
        \IntlChar::PROPERTY_HYPHEN,
        \IntlChar::PROPERTY_TERMINAL_PUNCTUATION,
        \IntlChar::PROPERTY_WHITE_SPACE,
        \IntlChar::PROPERTY_PATTERN_WHITE_SPACE,
        \IntlChar::PROPERTY_POSIX_BLANK,
        \IntlChar::PROPERTY_LINE_BREAK,
        \IntlChar::PROPERTY_SENTENCE_BREAK,
        \IntlChar::PROPERTY_WORD_BREAK,
        \IntlChar::PROPERTY_INVALID_CODE,
    ],
];
